-- 코드를 입력하세요
SELECT i.ANIMAL_ID,
       i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID=o.ANIMAL_ID
WHERE o.DATETIME IS NOT NULL AND
      DATEDIFF(i.DATETIME, o.DATETIME)
ORDER BY DATEDIFF(i.DATETIME, o.DATETIME) ASC
LIMIT 2;
