-- 코드를 입력하세요
SELECT CAR_ID,
       ROUND(AVG_DURATION, 1) AS AVERAGE_DURATION
FROM (
  SELECT CAR_ID,
         AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1) AS AVG_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  GROUP BY CAR_ID
) a
WHERE ROUND(AVG_DURATION, 1) >= 7
ORDER BY ROUND(AVG_DURATION, 1) DESC, CAR_ID DESC;