-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR,
       MONTH(s.SALES_DATE) AS MONTH,
       COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT s.USER_ID) * 1.0 / totals.total_2021_joined, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE s
JOIN USER_INFO u ON s.USER_ID = u.USER_ID AND YEAR(u.JOINED) = 2021
CROSS JOIN (
  SELECT COUNT(*) AS total_2021_joined
  FROM USER_INFO
  WHERE YEAR(JOINED) = 2021
) AS totals
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
ORDER BY YEAR, MONTH;