-- 코드를 입력하세요
SELECT a.PRODUCT_ID,
       a.PRODUCT_NAME,
       SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
     SELECT p.PRODUCT_ID,
            p.PRODUCT_NAME,
            p.PRICE * o.AMOUNT AS TOTAL_SALES
     FROM FOOD_PRODUCT p JOIN FOOD_ORDER o ON p.PRODUCT_ID=o.PRODUCT_ID
     WHERE o.PRODUCE_DATE LIKE "%2022-05%"
) a
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;